### ISSUE TITLE
EF Core 3 does not translate FuzzyEquals method

### ISSUE THREAD

**Issue by paulirwin** [feature23/odata-lite#3]
Error at runtime using EF Core 3, as it cannot translate FuzzyEquals method. May need to accept that in-memory string comparisons will be case-sensitive for now, and database string comparisons will use the collation of the database.

**Comment by jamesmblair** [comment]
I believe that EF Core 2 was also unable to translate FuzzyEquals, but the default behavior in 2.x was to silently perform the evaluation in memory. This could result in really bad, unexpected behavior, like attempting to load an entire database table into memory. EF Core 3.x changes the default behavior to throwing an exception.

I think we have to accept string comparisons on IQueryable using the database collation.

**Comment by paulirwin** [comment]
Agreed, made irrelevant by #4
